using SecureToolKitAPI.Contracts.Network;
using SecureToolKitAPI.Cryptography.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace SecureToolKitAPI.Controllers
{
    /// <summary>
    /// Generates the key material used to authenticate to remote machines. Generation lives in
    /// <see cref="INetworkKeyGenerator"/>; this controller maps the request and maps the result.
    /// </summary>
    /// <remarks>
    /// <para>
    /// SSH keys are the whole of what is implemented here. Two neighbours in the same functional group are
    /// deliberately absent, and it is worth saying why rather than leaving a gap: a PGP key is mostly a
    /// packet-format problem — a key is only useful once it is wrapped in OpenPGP packets with self
    /// signatures and user IDs, which is a format this API would have to assemble by hand — and a WireGuard
    /// key pair is X25519, which .NET does not expose. Ed25519 is missing from the SSH support for the same
    /// reason. In each case the alternative was to write the primitive or the container here, and a
    /// hand-rolled key is worse than a missing one.
    /// </para>
    /// <para>
    /// Generation is a POST because the response carries a private key, and a URL ends up in server logs,
    /// proxy logs and browser history. The key-type catalogue is a GET because it is fixed, public and the
    /// same for every caller.
    /// </para>
    /// <para>
    /// An SSH private key generated here has crossed a network, which one generated by <c>ssh-keygen</c> on
    /// the machine that will use it has not. That is a real difference and every response says so. This API
    /// does not store, log or cache any part of a key pair.
    /// </para>
    /// </remarks>
    [ApiController]
    [Route("api/network")]
    [Produces("application/json")]
    public class NetworkKeyController(INetworkKeyGenerator network) : ControllerBase
    {
        /// <summary>
        /// Generates an SSH key pair.
        /// </summary>
        /// <param name="request">
        /// Algorithm, size and comment. Omit the body for the default: an RSA 3072-bit key with no comment.
        /// </param>
        /// <returns>
        /// Returns the public key as a single <c>authorized_keys</c> line, the private key in PEM, and the
        /// <c>SHA256:</c> fingerprint of the pair.
        /// </returns>
        /// <remarks>
        /// The public half goes on the machine you want to reach and the private half never leaves the machine
        /// you connect from. The private key is returned unencrypted, so save it with owner-only permissions
        /// and add a passphrase with <c>ssh-keygen -p</c>. For production access, prefer generating the key
        /// with <c>ssh-keygen</c> where it will be used, so the private half never crosses a wire.
        /// </remarks>
        [HttpPost("ssh")]
        [ProducesResponseType<SshKeyResponse>(StatusCodes.Status200OK)]
        [ProducesResponseType<ProblemDetails>(StatusCodes.Status400BadRequest)]
        public IActionResult GenerateSshKey(
            [FromBody(EmptyBodyBehavior = EmptyBodyBehavior.Allow)] SshKeyRequest? request = null) =>
            Ok(ToResponse(network.GenerateSshKey(ToSpec(request))));

        /// <summary>
        /// Lists the SSH algorithm and size combinations this API will generate.
        /// </summary>
        /// <returns>Returns the catalogue, smallest size first within each algorithm.</returns>
        /// <remarks>
        /// A GET is safe here because nothing in the listing is secret or generated: it is the same set of
        /// combinations for every caller. Use it to discover the accepted values instead of guessing and
        /// reading the error message.
        /// </remarks>
        [HttpGet("ssh/key-types")]
        [ProducesResponseType<IReadOnlyList<SshKeyTypeResponse>>(StatusCodes.Status200OK)]
        public IActionResult GetSshKeyTypes() =>
            Ok(network.SshKeyTypes().Select(keyType => ToResponse(keyType)).ToArray());

        /// <summary>Maps the SSH request onto the generator's options.</summary>
        /// <param name="request">The request, or <c>null</c> when the body was omitted.</param>
        /// <remarks>
        /// The size is passed through as supplied rather than defaulted here, because the default depends on
        /// the algorithm and the spec is the one place that knows which default goes with which.
        /// </remarks>
        private static SshKeySpec ToSpec(SshKeyRequest? request)
        {
            var defaults = new SshKeySpec();

            if (request is null)
            {
                return defaults;
            }

            return new SshKeySpec
            {
                Algorithm = NetworkOptions.ParseSshAlgorithm(request.Algorithm),
                Bits = request.Bits,
                Comment = request.Comment
            };
        }

        /// <summary>Maps a generated SSH key pair onto the response contract.</summary>
        /// <param name="key">What the generator produced. Its private half is secret material.</param>
        private static SshKeyResponse ToResponse(GeneratedSshKey key) => new()
        {
            Algorithm = key.Algorithm,
            KeyType = key.KeyType,
            Bits = key.Bits,
            SecurityStrengthBits = key.SecurityStrengthBits,
            PublicKey = key.PublicKey,
            PrivateKey = key.PrivateKey,
            PrivateKeyFormat = key.PrivateKeyFormat,
            Fingerprint = key.Fingerprint,
            Comment = key.Comment,
            Composition = key.Composition,
            Warnings = key.Warnings
        };

        /// <summary>Maps one catalogue entry onto the response contract.</summary>
        /// <param name="keyType">The catalogue entry.</param>
        private static SshKeyTypeResponse ToResponse(SshKeyTypeInfo keyType) => new()
        {
            Algorithm = keyType.Algorithm,
            Bits = keyType.Bits,
            KeyType = keyType.KeyType,
            SecurityStrengthBits = keyType.SecurityStrengthBits,
            IsDefault = keyType.IsDefault,
            Notes = keyType.Notes
        };
    }
}
